### ISSUE TITLE
部署报错505

### ISSUE THREAD

**Issue by suyin-long** [hexojs/hexo-deployer-ftpsync#128]
报错代码如下：
```
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on  instance at:
    at Stream.<anonymous> (C:\Users\suyin\Desktop\Hexo-NexT\NexT\node_modules\jsftp\lib\jsftp.js:91:32)
    at Stream.emit (node:events:527:28)
    at Socket.reemit (C:\Users\suyin\Desktop\Hexo-NexT\NexT\node_modules\duplexer\index.js:85:16)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
```
求解？

**Comment by stevenjoezhang** [comment]
抱歉回复晚了，我已经重构了这个插件，如果问题仍然存在，欢迎继续报告。新版本的安装方法是： `npm i hexo-deployer-ftpsync@0.2.0`
