### ISSUE TITLE
ftpsync return Error 500 Unknown command

### ISSUE THREAD

**Issue by otherfish** [hexojs/hexo-deployer-ftpsync#13]
### this is errmsg:

```
INFO  Deploying: ftpsync
Setup
Setup complete.

Collecting
ftp.ls failed.
Collection failed.

FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: 530 You aren't logged in
    at Ftp.parse (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:233:11
)
    at Ftp.parseResponse (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.j
s:148:8)
    at Stream.<anonymous> (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.
js:119:24)
    at Stream.emit (events.js:107:17)
    at Stream.reemit (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\ev
ent-stream\node_modules\duplexer\index.js:70:25)
    at Stream.emit (events.js:107:17)
    at Stream.write (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\eve
nt-stream\index.js:192:12)
    at Stream.stream.write (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modu
les\event-stream\node_modules\through\index.js:26:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:107:17)
    at drain (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\event-stre
am\node_modules\through\index.js:36:16)
    at Stream.stream.queue.stream.push (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsf
tp\node_modules\event-stream\node_modules\through\index.js:45:5)
    at emit (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\event-strea
m\node_modules\split\index.js:35:14)
    at next (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\event-strea
m\node_modules\split\index.js:44:7)
    at Stream.<anonymous> (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modul
es\event-stream\node_modules\split\index.js:49:5)
    at Stream.stream.write (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modu
les\event-stream\node_modules\through\index.js:26:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
FATAL Error: 530 You aren't logged in
    at Ftp.parse (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.js:233:11
)
    at Ftp.parseResponse (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.j
s:148:8)
    at Stream.<anonymous> (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\lib\jsftp.
js:119:24)
    at Stream.emit (events.js:107:17)
    at Stream.reemit (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\ev
ent-stream\node_modules\duplexer\index.js:70:25)
    at Stream.emit (events.js:107:17)
    at Stream.write (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\eve
nt-stream\index.js:192:12)
    at Stream.stream.write (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modu
les\event-stream\node_modules\through\index.js:26:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:107:17)
    at drain (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\event-stre
am\node_modules\through\index.js:36:16)
    at Stream.stream.queue.stream.push (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsf
tp\node_modules\event-stream\node_modules\through\index.js:45:5)
    at emit (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\event-strea
m\node_modules\split\index.js:35:14)
    at next (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modules\event-strea
m\node_modules\split\index.js:44:7)
    at Stream.<anonymous> (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modul
es\event-stream\node_modules\split\index.js:49:5)
    at Stream.stream.write (E:\hexo\node_modules\hexo-deployer-ftpsync\node_modules\ftpsync\node_modules\jsftp\node_modu
les\event-stream\node_modules\through\index.js:26:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by leesei** [comment]
The error "530 You aren't logged in" seems clear to me.
Did you set `user` and `pass` in `_config.yml`?

**Comment by otherfish** [comment]
@leesei 
yeah, i'm sure i set the both `use` and `pass` field, but not works. i use the ftp tools to depoly now , this is too slow but also my pain point, thanks your reply

**Comment by leesei** [comment]
Can you check the server log?

**Comment by otherfish** [comment]
@leesei when you say check `user` and `pass` field  i am serious recheck them becase i can log into host by ftp softwave in the window os then i find the username is not include undersocre when i save the settings, so i try no undersocre on the `_config.yml` against `user` field it seems to be work but generate other error:

```
INFO  Deploying: ftpsync
Setup
Setup complete.

Collecting
Collection complete.

Consolidating
Consolidation complete.

Committing
ftp.put failed.
Additions failed.
Commit failed.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: 500 Unknown command
    at Ftp.parse (E:\hexo-new\node_modules\jsftp\lib\jsftp.js:233:11)
    at Ftp.parseResponse (E:\hexo-new\node_modules\jsftp\lib\jsftp.js:148:8)
    at Stream.<anonymous> (E:\hexo-new\node_modules\jsftp\lib\jsftp.js:119:24)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at Stream.reemit (E:\hexo-new\node_modules\duplexer\index.js:70:25)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at Stream.write (E:\hexo-new\node_modules\event-stream\index.js:192:12)
    at Stream.stream.write (E:\hexo-new\node_modules\through\index.js:26:11)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at drain (E:\hexo-new\node_modules\through\index.js:36:16)
    at Stream.stream.queue.stream.push (E:\hexo-new\node_modules\through\index.js:45:5)
    at emit (E:\hexo-new\node_modules\split\index.js:35:14)
    at next (E:\hexo-new\node_modules\split\index.js:44:7)
    at Stream.<anonymous> (E:\hexo-new\node_modules\split\index.js:49:5)
    at Stream.stream.write (E:\hexo-new\node_modules\through\index.js:26:11)
    at Socket.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
FATAL 500 Unknown command
Error: 500 Unknown command
    at Ftp.parse (E:\hexo-new\node_modules\jsftp\lib\jsftp.js:233:11)
    at Ftp.parseResponse (E:\hexo-new\node_modules\jsftp\lib\jsftp.js:148:8)
    at Stream.<anonymous> (E:\hexo-new\node_modules\jsftp\lib\jsftp.js:119:24)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at Stream.reemit (E:\hexo-new\node_modules\duplexer\index.js:70:25)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at Stream.write (E:\hexo-new\node_modules\event-stream\index.js:192:12)
    at Stream.stream.write (E:\hexo-new\node_modules\through\index.js:26:11)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at drain (E:\hexo-new\node_modules\through\index.js:36:16)
    at Stream.stream.queue.stream.push (E:\hexo-new\node_modules\through\index.js:45:5)
    at emit (E:\hexo-new\node_modules\split\index.js:35:14)
    at next (E:\hexo-new\node_modules\split\index.js:44:7)
    at Stream.<anonymous> (E:\hexo-new\node_modules\split\index.js:49:5)
    at Stream.stream.write (E:\hexo-new\node_modules\through\index.js:26:11)
    at Socket.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

**Comment by leesei** [comment]
Good, at least it can connect now.
Try set `verbose` to true.
You may need to review the log and redact sensitive info.

**Comment by otherfish** [comment]
@leesei well, when i set `verbose` to true. i am get the same error when process the commit

**Comment by leesei** [comment]
`verbose` is to show more logs, not to fix the issue.

**Comment by otherfish** [comment]
@leesei i know your meaning but the error is still exist i'm sure the setting `verbose` not to fix the issue

**Comment by leesei** [comment]
So is the log any difference?

**Comment by otherfish** [comment]
@leesei only errmsg more verbose no difference , this is errmsg:

      '/vendors/ua-parser-js/dist/ua-parser.min.js',
      '/vendors/ua-parser-js/dist/ua-parser.pack.js' ]

      Consolidation complete.

       Committing
       -------------------------------------------------------------
       - /2015/09/16/title/index.html uploaded successfuly
       - /2015/10/06/title/index.html uploaded successfuly
      Additions complete.
      - /2015/08/30/title/index.html uploaded successfuly
      - /2015/08/30/title/index.html uploaded successfuly
      ftp.put failed.
      Updates failed.
      Commit failed.
      FATAL Something's wrong. Maybe you can find the solution here:      
       http://hexo.io/docs/troubleshooting.html
      Error: read ECONNRESET
      at exports._errnoException (util.js:870:11)
      at TCP.onread (net.js:552:26)
      FATAL read ECONNRESET
      Error: read ECONNRESET
      at exports._errnoException (util.js:870:11)
      at TCP.onread (net.js:552:26)
