### ISSUE TITLE
The address set by FTP is inconsistent with the address of the connection

### ISSUE THREAD

**Issue by StringKe** [hexojs/hexo-deployer-ftpsync#29]
zh-CN:我设置的地址是我的外网IP,ftp工具是可以正常访问的,但是在hexo同步的时候它在连接我服务器的内网IP
en:The address I set is my external IP, FTP tool can be accessed normally, but when hexo synchronizes, it connects to my server's intranet IP.

```nodejs
Remove:
[]

Consolidation complete.

Committing
-------------------------------------------------------------
events.js:167
      throw er; // Unhandled 'error' event
      ^
                                            //这里是我的内网IP this is my Intranet IP
Error: connect ETIMEDOUT 172.18.221.72:47939
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

```

**Comment by StringKe** [comment]
servers network type is nat(dhcp)
