### ISSUE TITLE
deploy issue

### ISSUE THREAD

**Issue by yuxingmo** [hexojs/hexo-deployer-ftpsync#32]
After `hexo d`:

Committing
-------------------------------------------------------------
- /post/92d72c3a.html uploaded successfuly
Additions complete.
ftp.put failed.
Updates failed.
Commit failed.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: 421 Data timeout. Reconnect. Sorry.
    at module.exports.Ftp.parse (G:\OneDrive\Github\时光之笔\node_modules\jsftp\lib\jsftp.js:233:11)
    at module.exports.Ftp.parseResponse (G:\OneDrive\Github\时光之笔\node_modules\jsftp\lib\jsftp.js:148:8)
    at Stream.<anonymous> (G:\OneDrive\Github\时光之笔\node_modules\jsftp\lib\jsftp.js:119:24)
    at Stream.emit (events.js:189:13)
    at Stream.reemit (G:\OneDrive\Github\时光之笔\node_modules\duplexer\index.js:70:25)
    at Stream.emit (events.js:189:13)
    at Stream.write (G:\OneDrive\Github\时光之笔\node_modules\event-stream\index.js:192:12)
    at Stream.stream.write (G:\OneDrive\Github\时光之笔\node_modules\through\index.js:26:11)
    at Stream.ondata (internal/streams/legacy.js:15:31)
    at Stream.emit (events.js:189:13)
    at drain (G:\OneDrive\Github\时光之笔\node_modules\through\index.js:36:16)
    at Stream.stream.queue.stream.push (G:\OneDrive\Github\时光之笔\node_modules\through\index.js:45:5)
    at emit (G:\OneDrive\Github\时光之笔\node_modules\split\index.js:35:14)
    at next (G:\OneDrive\Github\时光之笔\node_modules\split\index.js:44:7)
    at Stream.<anonymous> (G:\OneDrive\Github\时光之笔\node_modules\split\index.js:49:5)
    at Stream.stream.write (G:\OneDrive\Github\时光之笔\node_modules\through\index.js:26:11)
    at Socket.ondata (_stream_readable.js:689:20)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by stevenjoezhang** [comment]
Sorry for the late reply. I am currently refactoring this plugin. If the problem still exists, please feel free to continue reporting. See #148
